; DAA WORKS ONLY IN AX REGISTER
; IF LOWER NIBBLE 
;     GREATER THAN 9 OR AUXILLARY CARRY IS 1, THEN ADD 06
; IF HIGHER NIBBLE 
;     GREATER THAN 9 OR CARRY FLAG IS 1, THEN ADD 60
CODE SEGMENT
    ASSUME CS:CODE
    START:  MOV AX, 2000H
            MOV DS, AX
            MOV AL, 25H
            MOV AH, 25H
            ADD AL, AH
            DAA
            INT 03H
CODE ENDS
    END START